# Gradient Calculation

In [9]:
import torch

x = torch.randn(3, requires_grad=True)
print(x)

y = x+2
print(y)
z = y*y*2
z = z.mean()
print(z)

z.backward() # dz/dx
print(x.grad)

tensor([-1.0475,  0.9980, -0.3144], requires_grad=True)
tensor([0.9525, 2.9980, 1.6856], grad_fn=<AddBackward0>)
tensor(8.4911, grad_fn=<MeanBackward0>)
tensor([1.2699, 3.9974, 2.2475])


# Vector and Jacobian product gives a scalar output (Chain Rule)
# When Vector is not provided see the error

In [10]:
import torch

x = torch.randn(3, requires_grad=True)
print(x)

y = x+2
print(y)
z = y*y*2
# z = z.mean()
print(z)

z.backward() # dz/dx
print(x.grad)

tensor([-0.9698,  0.2750, -1.5070], requires_grad=True)
tensor([1.0302, 2.2750, 0.4930], grad_fn=<AddBackward0>)
tensor([ 2.1228, 10.3511,  0.4860], grad_fn=<MulBackward0>)


RuntimeError: grad can be implicitly created only for scalar outputs

# Passing Vector to it

In [12]:
import torch

x = torch.randn(3, requires_grad=True)
print(x)

y = x+2
print(y)
z = y*y*2
# z = z.mean()
print(z)

v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)
z.backward(v) # dz/dx
print(x.grad)

tensor([-0.7692, -0.4341,  1.4996], requires_grad=True)
tensor([1.2308, 1.5659, 3.4996], grad_fn=<AddBackward0>)
tensor([ 3.0296,  4.9040, 24.4941], grad_fn=<MulBackward0>)
tensor([0.4923, 6.2635, 0.0140])


# Prevent PyTorch from tracking history and calculating "grad_fn" attribute

In [17]:
x = torch.randn(3, requires_grad=True)
print(x)

# x.requires_grad_(False)
# x.detach()
# with torch.no_grad():

# 1st option
x.requires_grad_(False) # Whenever a function has a trailing underscore in PyTorch then this means that it will modify our variable in place.
print(x)

# 2nd option
y = x.detach()
print(y)

# last option
with torch.no_grad():
    z = x+2
    print(z)

tensor([1.2785, 0.5412, 0.6923], requires_grad=True)
tensor([1.2785, 0.5412, 0.6923])
tensor([1.2785, 0.5412, 0.6923])
tensor([3.2785, 2.5412, 2.6923])
tensor([3.2785, 2.5412, 2.6923])


In [18]:
x = torch.randn(3, requires_grad=True)
print(x)

a = x+2
print(a)

tensor([ 0.3495, -0.6691,  0.7581], requires_grad=True)
tensor([2.3495, 1.3309, 2.7581], grad_fn=<AddBackward0>)


# Dummy Training example

In [24]:
import torch

weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weights*3).sum()

    model_output.backward()

    print(weights.grad)

    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


# PyTorch built-in Optimizer

In [ ]:
import torch

weights = torch.ones(4, requires_grad=True)

optimizer = torch.optim.SGD(weights, lr=0.01)
optimizer.step()
optimizer.zero_grad()