# 1. Created virtual environment and downloaded cuda, pytorch with cuda support into the virtual environment

# 2. Tensors

# 2.1 Empty Tensors

In [8]:
import torch

x1 = torch.empty(1)
print(x1)

tensor([1.4013e-45])


In [10]:
x2 = torch.empty(2, 2)
print(x2)

tensor([[inf, 0.],
        [0., 0.]])


In [11]:
x3 = torch.empty(2, 2, 3)
print(x3)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
