# 1. Created virtual environment and downloaded cuda, also downloaded PyTorch with cuda support in the virtual environment.

# 2. Tensors

# 2.1 Empty Tensors

In [1]:
import torch

# 1 inside small braces is like scaler value
x1 = torch.empty(1)
print(x1)

tensor([0.])


In [2]:
import torch

# 3 inside small braces is like 1D vector with three elements
x2 = torch.empty(3)
print(x2)

tensor([0., 0., 0.])


In [3]:
# two values inside small braces means 2D vector

x3 = torch.empty(2, 2)

print(x3)

tensor([[0., 0.],
        [0., 0.]])


In [4]:
# 3 dimension

x4 = torch.empty(2, 2, 3)
print(x4)

tensor([[[7.9959e-03, 1.0426e-42, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])


In [5]:
# 4 dimensions but can't print it anymore

# x5 = torch.empty(2, 2, 2, 3)
# print(x5)

In [6]:
print(torch.__version__)

2.12.0+cu132


# Tensor with random values

In [7]:
x6 = torch.rand(2,2)
print(x6)

tensor([[0.6139, 0.0828],
        [0.7413, 0.1967]])


# Tensor with all zeroes

In [8]:
x7 = torch.zeros(2,2)
print(x7)

tensor([[0., 0.],
        [0., 0.]])


# Tensor with all ones

In [9]:
x8 = torch.ones(2,2)
print(x8)

tensor([[1., 1.],
        [1., 1.]])


# Specific data type

In [10]:
x9 = torch.ones(2,2)
print(x9.dtype)

torch.float32


In [11]:
x10 = torch.ones(2,2, dtype=torch.int)
print(x10.dtype)

torch.int32


In [12]:
x11 = torch.ones(2,2, dtype=torch.double)
print(x11.dtype)

torch.float64


In [13]:
x12 = torch.ones(2,2, dtype=torch.float16)
print(x12.dtype)

torch.float16


# Size

In [14]:
x13 = torch.ones(2,2, dtype=torch.int)
print(x13.size())

torch.Size([2, 2])


# Construct a Tensor from data

In [15]:
x14 = torch.tensor([2.5, 0.1])
print(x14)

tensor([2.5000, 0.1000])


# Some Basic Operations

In [16]:
# Addition
a1 = torch.rand(2,2)
a2 = torch.rand(2,2)
print(a1)
print(a2)
a3 = a1 + a2
print(a3)

# Or
a4 = torch.add(a1,a2)
print(a4)

tensor([[0.5655, 0.4513],
        [0.0116, 0.6436]])
tensor([[0.0722, 0.5511],
        [0.8593, 0.3689]])
tensor([[0.6377, 1.0024],
        [0.8709, 1.0125]])
tensor([[0.6377, 1.0024],
        [0.8709, 1.0125]])


In [17]:
# Subtraction
a4 = torch.rand(2,2)
a5 = torch.rand(2,2)

a6 = a4 - a5
print(a6)

# Or
a7 = torch.sub(a4, a5)
print(a7)

tensor([[-0.0267, -0.2117],
        [ 0.2329,  0.6493]])
tensor([[-0.0267, -0.2117],
        [ 0.2329,  0.6493]])


In [18]:
# Multiplication
a8 = torch.rand(2,2)
a9 = torch.rand(2,2)

a10 = a8 * a9
print(a10)

# Or
a11 = torch.mul(a8, a9)
print(a11)

tensor([[0.1106, 0.3776],
        [0.2150, 0.5290]])
tensor([[0.1106, 0.3776],
        [0.2150, 0.5290]])


In [19]:
# Division
a12 = torch.rand(2,2)
a13 = torch.rand(2,2)

a14 = a12/a13
print(a14)

# Or
a15 = torch.div(a12,a13)
print(a15)

tensor([[6.5986, 1.9315],
        [0.4709, 1.1842]])
tensor([[6.5986, 1.9315],
        [0.4709, 1.1842]])


# In-place operation

In [20]:
# Addition
# a1 = torch.rand(2,2)
# a2 = torch.rand(2,2)
a1.add_(a2)
print(a1)

tensor([[0.6377, 1.0024],
        [0.8709, 1.0125]])


In [21]:
# Subtraction
# a4 = torch.rand(2,2)
# a5 = torch.rand(2,2)

a4.sub_(a5)
print(a4)

tensor([[-0.0267, -0.2117],
        [ 0.2329,  0.6493]])


In [22]:
# Multiplication
# a8 = torch.rand(2,2)
# a9 = torch.rand(2,2)
a8.mul_(a9)
print(a8)

tensor([[0.1106, 0.3776],
        [0.2150, 0.5290]])


In [23]:
# Division
# a12 = torch.rand(2,2)
# a13 = torch.rand(2,2)
a12.div_(a13)
print(a12)

tensor([[6.5986, 1.9315],
        [0.4709, 1.1842]])


# Slicing Operation

In [24]:
b1 = torch.rand(5,3)
print(b1)
# For all columns
print(b1[:,0])

tensor([[0.1788, 0.0919, 0.4316],
        [0.8281, 0.2115, 0.0658],
        [0.9328, 0.1905, 0.3349],
        [0.1443, 0.9011, 0.0892],
        [0.7651, 0.8936, 0.5365]])
tensor([0.1788, 0.8281, 0.9328, 0.1443, 0.7651])


In [25]:
# For all rows
print(b1[0,:])

tensor([0.1788, 0.0919, 0.4316])


In [26]:
print(b1[1,1])

tensor(0.2115)


In [28]:
# Can be used when only one element in the tensor, to get the value actually stored in the tensor
print(b1[1,1].item())

0.21145743131637573


# Reshaping a tensor

In [30]:
b2 = torch.rand(4,4)
print(b2)
b3 = b2.view(16)
print(b3)

tensor([[0.8673, 0.4586, 0.5987, 0.2292],
        [0.9509, 0.6506, 0.8286, 0.9479],
        [0.5406, 0.3841, 0.3796, 0.9227],
        [0.9583, 0.5233, 0.9028, 0.0266]])
tensor([0.8673, 0.4586, 0.5987, 0.2292, 0.9509, 0.6506, 0.8286, 0.9479, 0.5406,
        0.3841, 0.3796, 0.9227, 0.9583, 0.5233, 0.9028, 0.0266])


In [32]:
# if don't want to determine the size use this style

b4 = torch.rand(4,4)
print(b4)
b5 = b4.view(-1,8)
# (-1,8), here 8 states the no. of element in the row and rest the dimension pytorch will determine
print(b5)
print(b5.size())

tensor([[0.1892, 0.6057, 0.6907, 0.9792],
        [0.9055, 0.2730, 0.9505, 0.2305],
        [0.5231, 0.3307, 0.9813, 0.1888],
        [0.5446, 0.9498, 0.9112, 0.4762]])
tensor([[0.1892, 0.6057, 0.6907, 0.9792, 0.9055, 0.2730, 0.9505, 0.2305],
        [0.5231, 0.3307, 0.9813, 0.1888, 0.5446, 0.9498, 0.9112, 0.4762]])
torch.Size([2, 8])


# numpy to torch tensors and vice versa

In [34]:
import numpy as np

In [36]:
b6 = torch.ones(5)
print(b6)

b7 = b6.numpy()
print(b7)

# type
print(type(b7))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
