# 1. Created virtual environment and downloaded cuda, also downloaded PyTorch with cuda support in the virtual environment.

# 2. Tensors

# 2.1 Empty Tensors

In [2]:
import torch

x1 = torch.empty(1)
print(x1)

tensor([0.])


In [3]:
x2 = torch.empty(2, 2)
print(x2)

tensor([[0., 0.],
        [0., 0.]])


In [4]:
x3 = torch.empty(2, 2, 3)
print(x3)

tensor([[[5.4947e+08, 1.1098e-42, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])


In [7]:
# Corrected the virtual environment again today which takes all the time

In [8]:
torch.cuda.is_available()

False