# 1. Created virtual environment and downloaded cuda, also downloaded PyTorch with cuda support in the virtual environment.

# 2. Tensors

# 2.1 Empty Tensors

In [1]:
import torch

# 1 inside small braces is like scaler value
x1 = torch.empty(1)
print(x1)

tensor([0.])


In [2]:
# import torch

# 3 inside small braces is like 1D vector with three elements
x2 = torch.empty(3)
print(x2)

tensor([0., 0., 0.])


In [3]:
# two values inside small braces means 2D vector

x3 = torch.empty(2, 2)

print(x3)

tensor([[0., 0.],
        [0., 0.]])


In [4]:
# 3 dimension

x4 = torch.empty(2, 2, 3)
print(x4)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [5]:
# 4 dimensions but can't print it anymore

# x5 = torch.empty(2, 2, 2, 3)
# print(x5)

In [6]:
print(torch.__version__)

2.12.0+cu132


# Tensor with random values

In [7]:
x6 = torch.rand(2,2)
print(x6)

tensor([[0.3044, 0.0776],
        [0.7702, 0.8814]])


# Tensor with all zeroes

In [8]:
x7 = torch.zeros(2,2)
print(x7)

tensor([[0., 0.],
        [0., 0.]])


# Tensor with all ones

In [9]:
x8 = torch.ones(2,2)
print(x8)

tensor([[1., 1.],
        [1., 1.]])


# Specific data type

In [10]:
x9 = torch.ones(2,2)
print(x9.dtype)

torch.float32


In [11]:
x10 = torch.ones(2,2, dtype=torch.int)
print(x10.dtype)

torch.int32


In [12]:
x11 = torch.ones(2,2, dtype=torch.double)
print(x11.dtype)

torch.float64


In [13]:
x12 = torch.ones(2,2, dtype=torch.float16)
print(x12.dtype)

torch.float16


# Size

In [14]:
x13 = torch.ones(2,2, dtype=torch.int)
print(x13.size())

torch.Size([2, 2])


# Construct a Tensor from data

In [15]:
x14 = torch.tensor([2.5, 0.1])
print(x14)

tensor([2.5000, 0.1000])


# Some Basic Operations

In [16]:
# Addition
a1 = torch.rand(2,2)
a2 = torch.rand(2,2)
print(a1)
print(a2)
a3 = a1 + a2
print(a3)

# Or
a4 = torch.add(a1,a2)
print(a4)

tensor([[0.9826, 0.4980],
        [0.3025, 0.1375]])
tensor([[0.7089, 0.9818],
        [0.8801, 0.7712]])
tensor([[1.6916, 1.4797],
        [1.1825, 0.9087]])
tensor([[1.6916, 1.4797],
        [1.1825, 0.9087]])


In [17]:
# Subtraction
a4 = torch.rand(2,2)
a5 = torch.rand(2,2)

a6 = a4 - a5
print(a6)

# Or
a7 = torch.sub(a4, a5)
print(a7)

tensor([[ 0.2738,  0.3778],
        [ 0.3956, -0.2866]])
tensor([[ 0.2738,  0.3778],
        [ 0.3956, -0.2866]])


In [18]:
# Multiplication
a8 = torch.rand(2,2)
a9 = torch.rand(2,2)

a10 = a8 * a9
print(a10)

# Or
a11 = torch.mul(a8, a9)
print(a11)

tensor([[0.2828, 0.0296],
        [0.0624, 0.3842]])
tensor([[0.2828, 0.0296],
        [0.0624, 0.3842]])


In [19]:
# Division
a12 = torch.rand(2,2)
a13 = torch.rand(2,2)

a14 = a12/a13
print(a14)

# Or
a15 = torch.div(a12,a13)
print(a15)

tensor([[0.4605, 0.7656],
        [1.9037, 7.6202]])
tensor([[0.4605, 0.7656],
        [1.9037, 7.6202]])


# In-place operation

In [20]:
# Addition
# a1 = torch.rand(2,2)
# a2 = torch.rand(2,2)
a1.add_(a2)
print(a1)

tensor([[1.6916, 1.4797],
        [1.1825, 0.9087]])


In [21]:
# Subtraction
# a4 = torch.rand(2,2)
# a5 = torch.rand(2,2)

a4.sub_(a5)
print(a4)

tensor([[ 0.2738,  0.3778],
        [ 0.3956, -0.2866]])


In [22]:
# Multiplication
# a8 = torch.rand(2,2)
# a9 = torch.rand(2,2)
a8.mul_(a9)
print(a8)

tensor([[0.2828, 0.0296],
        [0.0624, 0.3842]])


In [23]:
# Division
# a12 = torch.rand(2,2)
# a13 = torch.rand(2,2)
a12.div_(a13)
print(a12)

tensor([[0.4605, 0.7656],
        [1.9037, 7.6202]])


# Slicing Operation

In [24]:
b1 = torch.rand(5,3)
print(b1)
# For all columns
print(b1[:,0])

tensor([[0.8378, 0.4714, 0.7497],
        [0.7205, 0.5592, 0.4761],
        [0.9391, 0.2681, 0.2661],
        [0.5534, 0.3269, 0.8198],
        [0.0415, 0.4896, 0.9466]])
tensor([0.8378, 0.7205, 0.9391, 0.5534, 0.0415])


In [25]:
# For all rows
print(b1[0,:])

tensor([0.8378, 0.4714, 0.7497])


In [26]:
print(b1[1,1])

tensor(0.5592)


In [27]:
# Can be used when only one element in the tensor, to get the value actually stored in the tensor
print(b1[1,1].item())

0.5592396855354309


# Reshaping a tensor

In [28]:
b2 = torch.rand(4,4)
print(b2)
b3 = b2.view(16)
print(b3)

tensor([[0.4921, 0.7955, 0.9280, 0.2008],
        [0.3377, 0.0422, 0.3676, 0.1612],
        [0.7369, 0.6917, 0.5879, 0.5813],
        [0.5915, 0.6671, 0.2230, 0.3497]])
tensor([0.4921, 0.7955, 0.9280, 0.2008, 0.3377, 0.0422, 0.3676, 0.1612, 0.7369,
        0.6917, 0.5879, 0.5813, 0.5915, 0.6671, 0.2230, 0.3497])


In [29]:
# if don't want to determine the size use this style

b4 = torch.rand(4,4)
print(b4)
b5 = b4.view(-1,8)
# (-1,8), here 8 states the no. of element in the row and rest the dimension pytorch will determine
print(b5)
print(b5.size())

tensor([[0.1652, 0.3755, 0.2507, 0.1840],
        [0.0880, 0.8678, 0.5998, 0.6020],
        [0.9444, 0.6127, 0.0959, 0.4301],
        [0.4586, 0.1533, 0.7501, 0.5534]])
tensor([[0.1652, 0.3755, 0.2507, 0.1840, 0.0880, 0.8678, 0.5998, 0.6020],
        [0.9444, 0.6127, 0.0959, 0.4301, 0.4586, 0.1533, 0.7501, 0.5534]])
torch.Size([2, 8])


# torch tensors to numpy array

In [30]:
import numpy as np

In [31]:
b6 = torch.ones(5)
print(b6)

b7 = b6.numpy()
print(b7)

# type
print(type(b7))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


# if tensor is on the cpu and not gpu then both objects share the same memory location, this means if we change one we will also change the other. For ex:- 

# Modify 'b7' or 'b6' in-place

In [32]:
# All the underscore functions will modify our variable in-place.
b6.add_(1)
# Take a look at tensor b6,
print(b6)
# Now also have a look at our numpy array,
print(b7)

# This happens because they both point to same memory location.

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


# numpy array to torch tensors

In [33]:
b8 = np.ones(5)
print(b8)
b9 = torch.from_numpy(b8)
print(b9)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [42]:
# To specify data type

b10 = torch.from_numpy(b8).int()
print(b10)

tensor([1, 1, 1, 1, 1], dtype=torch.int32)


In [43]:
b8 += 1
# if we print b8
print(b8)

[2. 2. 2. 2. 2.]


In [44]:
print(b9)
# The b9 also get incremented

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# When it is needed to calculate the gradients for the tensor later in the optimization steps

In [45]:
c = torch.ones(5, requires_grad=True)
print(c)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
