# 1. Created virtual environment and downloaded cuda, also downloaded PyTorch with cuda support in the virtual environment.

# 2. Tensors

# 2.1 Empty Tensors

In [4]:
import torch

# 1 inside small braces is like scaler value
x1 = torch.empty(1)
print(x1)

tensor([1.3856e+11])


In [12]:
import torch

# 3 inside small braces is like 1D vector with three elements
x2 = torch.empty(3)
print(x2)

tensor([-9.2390e-15,  7.5523e+06,  0.0000e+00])


In [13]:
# two values inside small braces means 2D vector

x3 = torch.empty(2, 2)

print(x3)

tensor([[0., 0.],
        [0., 0.]])


In [14]:
# 3 dimension

x4 = torch.empty(2, 2, 3)
print(x4)

tensor([[[1.4068e+11, 2.0907e-42, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])


In [15]:
# 4 dimensions but can't print it anymore

# x5 = torch.empty(2, 2, 2, 3)
# print(x5)

In [16]:
print(torch.__version__)

2.12.0+cu132


# Tensor with random values

In [17]:
x6 = torch.rand(2,2)
print(x6)

tensor([[0.4752, 0.9539],
        [0.6074, 0.5575]])


# Tensor with all zeroes

In [18]:
x7 = torch.zeros(2,2)
print(x7)

tensor([[0., 0.],
        [0., 0.]])


# Tensor with all ones

In [20]:
x8 = torch.ones(2,2)
print(x8)

tensor([[1., 1.],
        [1., 1.]])


# Specific data type

In [21]:
x9 = torch.ones(2,2)
print(x9.dtype)

torch.float32


In [25]:
x10 = torch.ones(2,2, dtype=torch.int)
print(x10.dtype)

torch.int32


In [26]:
x11 = torch.ones(2,2, dtype=torch.double)
print(x11.dtype)

torch.float64


In [27]:
x12 = torch.ones(2,2, dtype=torch.float16)
print(x12.dtype)

torch.float16


# Size

In [28]:
x13 = torch.ones(2,2, dtype=torch.int)
print(x13.size())

torch.Size([2, 2])


# Construct a Tensor from data

In [30]:
x14 = torch.tensor([2.5, 0.1])
print(x14)

tensor([2.5000, 0.1000])


# Some Basic Operations