# 1. Created virtual environment and downloaded cuda, also downloaded PyTorch with cuda support in the virtual environment.

# 2. Tensors

# 2.1 Empty Tensors

In [1]:
import torch

# 1 inside small braces is like scaler value
x1 = torch.empty(1)
print(x1)

tensor([0.])


In [2]:
import torch

# 3 inside small braces is like 1D vector with three elements
x2 = torch.empty(3)
print(x2)

tensor([0., 0., 0.])


In [3]:
# two values inside small braces means 2D vector

x3 = torch.empty(2, 2)

print(x3)

tensor([[0., 0.],
        [0., 0.]])


In [4]:
# 3 dimension

x4 = torch.empty(2, 2, 3)
print(x4)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [5]:
# 4 dimensions but can't print it anymore

# x5 = torch.empty(2, 2, 2, 3)
# print(x5)

In [6]:
print(torch.__version__)

2.12.0+cu132


# Tensor with random values

In [7]:
x6 = torch.rand(2,2)
print(x6)

tensor([[0.8217, 0.7796],
        [0.0972, 0.0015]])


# Tensor with all zeroes

In [8]:
x7 = torch.zeros(2,2)
print(x7)

tensor([[0., 0.],
        [0., 0.]])


# Tensor with all ones

In [9]:
x8 = torch.ones(2,2)
print(x8)

tensor([[1., 1.],
        [1., 1.]])


# Specific data type

In [10]:
x9 = torch.ones(2,2)
print(x9.dtype)

torch.float32


In [11]:
x10 = torch.ones(2,2, dtype=torch.int)
print(x10.dtype)

torch.int32


In [12]:
x11 = torch.ones(2,2, dtype=torch.double)
print(x11.dtype)

torch.float64


In [13]:
x12 = torch.ones(2,2, dtype=torch.float16)
print(x12.dtype)

torch.float16


# Size

In [14]:
x13 = torch.ones(2,2, dtype=torch.int)
print(x13.size())

torch.Size([2, 2])


# Construct a Tensor from data

In [15]:
x14 = torch.tensor([2.5, 0.1])
print(x14)

tensor([2.5000, 0.1000])


# Some Basic Operations

In [16]:
# Addition
a1 = torch.rand(2,2)
a2 = torch.rand(2,2)
print(a1)
print(a2)
a3 = a1 + a2
print(a3)

# Or
a4 = torch.add(a1,a2)
print(a4)

tensor([[0.4653, 0.1746],
        [0.7542, 0.9523]])
tensor([[0.3343, 0.4738],
        [0.6616, 0.9631]])
tensor([[0.7995, 0.6484],
        [1.4157, 1.9154]])
tensor([[0.7995, 0.6484],
        [1.4157, 1.9154]])


In [17]:
# Subtraction
a4 = torch.rand(2,2)
a5 = torch.rand(2,2)

a6 = a4 - a5
print(a6)

# Or
a7 = torch.sub(a4, a5)
print(a7)

tensor([[-0.3464,  0.4875],
        [-0.8519, -0.3485]])
tensor([[-0.3464,  0.4875],
        [-0.8519, -0.3485]])


In [18]:
# Multiplication
a8 = torch.rand(2,2)
a9 = torch.rand(2,2)

a10 = a8 * a9
print(a10)

# Or
a11 = torch.mul(a8, a9)
print(a11)

tensor([[0.2261, 0.2507],
        [0.3479, 0.4126]])
tensor([[0.2261, 0.2507],
        [0.3479, 0.4126]])


In [19]:
# Division
a12 = torch.rand(2,2)
a13 = torch.rand(2,2)

a14 = a12/a13
print(a14)

# Or
a15 = torch.div(a12,a13)
print(a15)

tensor([[2.2458, 0.3281],
        [1.0287, 1.0191]])
tensor([[2.2458, 0.3281],
        [1.0287, 1.0191]])


# In-place operation

In [20]:
# Addition
# a1 = torch.rand(2,2)
# a2 = torch.rand(2,2)
a1.add_(a2)
print(a1)

tensor([[0.7995, 0.6484],
        [1.4157, 1.9154]])


In [21]:
# Subtraction
# a4 = torch.rand(2,2)
# a5 = torch.rand(2,2)

a4.sub_(a5)
print(a4)

tensor([[-0.3464,  0.4875],
        [-0.8519, -0.3485]])


In [22]:
# Multiplication
# a8 = torch.rand(2,2)
# a9 = torch.rand(2,2)
a8.mul_(a9)
print(a8)

tensor([[0.2261, 0.2507],
        [0.3479, 0.4126]])


In [23]:
# Division
# a12 = torch.rand(2,2)
# a13 = torch.rand(2,2)
a12.div_(a13)
print(a12)

tensor([[2.2458, 0.3281],
        [1.0287, 1.0191]])


# Slicing Operation

In [24]:
b1 = torch.rand(5,3)
print(b1)
# For all columns
print(b1[:,0])

tensor([[1.9432e-01, 4.9921e-02, 9.8929e-01],
        [7.6459e-01, 6.3547e-02, 5.4329e-01],
        [7.9426e-01, 3.6431e-01, 5.4961e-04],
        [8.2254e-01, 4.8899e-01, 7.6197e-01],
        [6.1598e-01, 1.4181e-01, 7.3480e-01]])
tensor([0.1943, 0.7646, 0.7943, 0.8225, 0.6160])


In [25]:
# For all rows
print(b1[0,:])

tensor([0.1943, 0.0499, 0.9893])


In [26]:
print(b1[1,1])

tensor(0.0635)


In [27]:
# Can be used when only one element in the tensor, to get the value actually stored in the tensor
print(b1[1,1].item())

0.06354737281799316


# Reshaping a tensor

In [28]:
b2 = torch.rand(4,4)
print(b2)
b3 = b2.view(16)
print(b3)

tensor([[0.4831, 0.7576, 0.7042, 0.4702],
        [0.4790, 0.3002, 0.6484, 0.3068],
        [0.0676, 0.9864, 0.5477, 0.9130],
        [0.9055, 0.6275, 0.2912, 0.7722]])
tensor([0.4831, 0.7576, 0.7042, 0.4702, 0.4790, 0.3002, 0.6484, 0.3068, 0.0676,
        0.9864, 0.5477, 0.9130, 0.9055, 0.6275, 0.2912, 0.7722])


In [29]:
# if don't want to determine the size use this style

b4 = torch.rand(4,4)
print(b4)
b5 = b4.view(-1,8)
# (-1,8), here 8 states the no. of element in the row and rest the dimension pytorch will determine
print(b5)
print(b5.size())

tensor([[0.8352, 0.4778, 0.4979, 0.9820],
        [0.1641, 0.9160, 0.5412, 0.7346],
        [0.4216, 0.3650, 0.8842, 0.7542],
        [0.6635, 0.2281, 0.4780, 0.9500]])
tensor([[0.8352, 0.4778, 0.4979, 0.9820, 0.1641, 0.9160, 0.5412, 0.7346],
        [0.4216, 0.3650, 0.8842, 0.7542, 0.6635, 0.2281, 0.4780, 0.9500]])
torch.Size([2, 8])


# torch tensors to numpy array

In [30]:
import numpy as np

In [38]:
b6 = torch.ones(5)
print(b6)

b7 = b6.numpy()
print(b7)

# type
print(type(b7))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


# if tensor is on the cpu and not gpu then both objects share the same memory location, this means if we change one we will also change the other. For ex:- 

# Modify 'b7' or 'b6' in-place

In [39]:
# All the underscore functions will modify our variable in-place.
b6.add_(1)
# Take a look at tensor b6,
print(b6)
# Now also have a look at our numpy array,
print(b7)

# This happens because they both point to same memory location.

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


# numpy array to torch tensors

In [40]:
b8 = np.ones(5)
print(b8)
b9 = torch.from_numpy(b8)
print(b9)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [47]:
# To specify data type

b10 = np.ones(5)
print(b10)
b11 = torch.from_numpy(b10, dtype=torch.int)
print(b11.dtype)

[1. 1. 1. 1. 1.]


TypeError: torch._VariableFunctionsClass.from_numpy() takes no keyword arguments