# Gradient Calculation

In [1]:
import torch

x = torch.rand(3, requires_grad=True)
print(x)

y = x + 2
print(y)
z = y*y*2
z = z.mean()
print(z)

z.backward() #dz/dx
print(x.grad)

tensor([0.3504, 0.3992, 0.9772], requires_grad=True)
tensor([2.3504, 2.3992, 2.9772], grad_fn=<AddBackward0>)
tensor(13.4295, grad_fn=<MeanBackward0>)
tensor([3.1339, 3.1989, 3.9695])
