# 1. Created virtual environment and downloaded cuda, also downloaded PyTorch with cuda support in the virtual environment.

# 2. Tensors

# 2.1 Empty Tensors

In [1]:
import torch

# 1 inside small braces is like scaler value
x1 = torch.empty(1)
print(x1)

tensor([0.])


In [2]:
import torch

# 3 inside small braces is like 1D vector with three elements
x2 = torch.empty(3)
print(x2)

tensor([0., 0., 0.])


In [3]:
# two values inside small braces means 2D vector

x3 = torch.empty(2, 2)

print(x3)

tensor([[0., 0.],
        [0., 0.]])


In [4]:
# 3 dimension

x4 = torch.empty(2, 2, 3)
print(x4)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [5]:
# 4 dimensions but can't print it anymore

# x5 = torch.empty(2, 2, 2, 3)
# print(x5)

In [6]:
print(torch.__version__)

2.12.0+cu132


# Tensor with random values

In [7]:
x6 = torch.rand(2,2)
print(x6)

tensor([[0.7574, 0.9035],
        [0.6889, 0.3124]])


# Tensor with all zeroes

In [8]:
x7 = torch.zeros(2,2)
print(x7)

tensor([[0., 0.],
        [0., 0.]])


# Tensor with all ones

In [9]:
x8 = torch.ones(2,2)
print(x8)

tensor([[1., 1.],
        [1., 1.]])


# Specific data type

In [10]:
x9 = torch.ones(2,2)
print(x9.dtype)

torch.float32


In [11]:
x10 = torch.ones(2,2, dtype=torch.int)
print(x10.dtype)

torch.int32


In [12]:
x11 = torch.ones(2,2, dtype=torch.double)
print(x11.dtype)

torch.float64


In [13]:
x12 = torch.ones(2,2, dtype=torch.float16)
print(x12.dtype)

torch.float16


# Size

In [14]:
x13 = torch.ones(2,2, dtype=torch.int)
print(x13.size())

torch.Size([2, 2])


# Construct a Tensor from data

In [15]:
x14 = torch.tensor([2.5, 0.1])
print(x14)

tensor([2.5000, 0.1000])


# Some Basic Operations

In [49]:
# Addition
a1 = torch.rand(2,2)
a2 = torch.rand(2,2)
print(a1)
print(a2)
a3 = a1 + a2
print(a3)

# Or
a4 = torch.add(a1,a2)
print(a4)

tensor([[0.4614, 0.5124],
        [0.4653, 0.3001]])
tensor([[0.1451, 0.9319],
        [0.9096, 0.4328]])
tensor([[0.6066, 1.4443],
        [1.3749, 0.7329]])
tensor([[0.6066, 1.4443],
        [1.3749, 0.7329]])


In [50]:
# Subtraction
a4 = torch.rand(2,2)
a5 = torch.rand(2,2)

a6 = a4 - a5
print(a6)

# Or
a7 = torch.sub(a4, a5)
print(a7)

tensor([[0.2176, 0.0202],
        [0.2272, 0.4312]])
tensor([[0.2176, 0.0202],
        [0.2272, 0.4312]])


In [51]:
# Multiplication
a8 = torch.rand(2,2)
a9 = torch.rand(2,2)

a10 = a8 * a9
print(a10)

# Or
a11 = torch.mul(a8, a9)
print(a11)

tensor([[0.0546, 0.7009],
        [0.2288, 0.1414]])
tensor([[0.0546, 0.7009],
        [0.2288, 0.1414]])


In [52]:
# Division
a12 = torch.rand(2,2)
a13 = torch.rand(2,2)

a14 = a12/a13
print(a14)

# Or
a15 = torch.div(a12,a13)
print(a15)

tensor([[0.5591, 3.4003],
        [1.4613, 4.1412]])
tensor([[0.5591, 3.4003],
        [1.4613, 4.1412]])


# In-place operation

In [53]:
# Addition
# a1 = torch.rand(2,2)
# a2 = torch.rand(2,2)
a1.add_(a2)
print(a1)

tensor([[0.6066, 1.4443],
        [1.3749, 0.7329]])


In [54]:
# Subtraction
# a4 = torch.rand(2,2)
# a5 = torch.rand(2,2)

a4.sub_(a5)
print(a4)

tensor([[0.2176, 0.0202],
        [0.2272, 0.4312]])


In [55]:
# Multiplication
# a8 = torch.rand(2,2)
# a9 = torch.rand(2,2)
a8.mul_(a9)
print(a8)

tensor([[0.0546, 0.7009],
        [0.2288, 0.1414]])


In [56]:
# Division
# a12 = torch.rand(2,2)
# a13 = torch.rand(2,2)
a12.div_(a13)
print(a12)

tensor([[0.5591, 3.4003],
        [1.4613, 4.1412]])


# Slicing Operation